name: Docker Image CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 0"

jobs:

  build:
    name: Build and push to DockerHub
    runs-on: ubuntu-latest
    # lol
    strategy:
      matrix:
        folder: ["pwntools/py2", "pwntools/py3"]
        include:
          - folder: "pwntools/py2"
            tag: "pwntools"
            version: 2
            # latest pwntools
          - folder: "pwntools/py3"
            tag: "pwntools"
            version: 3
            latest: true

    steps:
    
    - name: Checkout main repository
      uses: actions/checkout@v2
      
    - name: Build the image
      run: docker build --tag deltaclock/${{ matrix.tag }}:${{ matrix.version }} ${{ matrix.folder }}
    
        
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push to DockerHub
      run: docker push deltaclock/${{ matrix.tag }}:${{ matrix.version }}

