name: Docker Image CI

on:
  push:
    branches: [master]
  schedule:
    # every week
    - cron: "0 0 * * 0"

jobs:
  build:
    name: Build and push to DockerHub
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: ["pwntools/py2", "pwntools/py3", "rsactftool", "qiling/stable", "qiling/dev"]
        include:
          - folder: "pwntools/py2"
            tag: "pwntools"
            version: 2
            # latest pwntools
          - folder: "pwntools/py3"
            tag: "pwntools"
            version: 3
            latest: true
            # rsactftool using py3.8
          - folder: "rsactftool"
            tag: "rsactftool"
            version: 3.8
            latest: true
            # qiling
          - folder: "qiling/stable"
            tag: "qiling"
            version: "stable"
          - folder: "qiling/dev"
            tag: "qiling"
            version: "dev"
            latest: true
          

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: true
          context: ${{ matrix.folder }}
          tags: deltaclock/${{ matrix.tag }}:${{ matrix.version }}

      - name: Tag and push the latest image
        if: matrix.latest
        run: |
          docker tag deltaclock/${{ matrix.tag }}:${{ matrix.version }} deltaclock/${{ matrix.tag }}:latest
          docker push deltaclock/${{ matrix.tag }}:latest
